print("Hello there, I can create you a story!")
name = input("What is your name? ")
if name == "Mattie Simone":
    print("Hello divine creator, I am glad to see you again. ")
else:
    print(f"Hello {name}, lets create your story!")
print("                                                                                                     ")
print("                                                                                                     ")

main = input("Could you give me an animal (not capital): ")
aan = input("Now would a or an be followed by that animals name? (not capital): ")
gender = input("A gender you would like this animal to go by like They or He (capital): ")
theme = input("Now give me a descriptive word, like dreamy or foggy (not capital): ")
emotion = input("Now an emotion this animal might be feeling edning in ly (not capital): ")
setting = input("And could you give me an on land terrain, like forest or desert(not capital): ")
food = input("And finally, would you give me an edible plant or berry that would grow in that place (not capital):")
print("Awesome!, here's your story:")
print("                                                                                                     ")
print("                                                                                                     ")
print("~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*")
print(f"One {theme} night {aan} {main} was floating above the {setting}, {gender} walked on the air {emotion}.")
print(f"{gender} flew down and picked some {food} from the {setting}.")
print(f"{gender} looked up and saw that the sun was just falling under the horizon, and the stars were already peeking out from the pink sky.")
print("~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*~~*")
print("                                                                                                     ")